all:
	gcc test.c test_grammar.c test_housekeeping.c test_stack.c neillsdl2.c -o test -Wall -Werror -std=c99 -pedantic -lSDL2

test:
	gcc test.c test_grammar.c test_housekeeping.c test_stack.c neillsdl2.c -o test -Wall -Werror -std=c99 -pedantic -lSDL2

clean:
	rm -f test